language: node_js
dist: trusty
sudo: required
node_js: 5
install:
  - npm install bower -g
  - npm install
  - bower install
script:
  - node ./test-server.js &
  - sleep 2 && pulp test
after_success:
- >-
  test $TRAVIS_TAG &&
  node_modules/.bin/psc-publish > .pursuit.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @.pursuit.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
